const data = [
  {
    title: "Cozy Mountain Cabin",
    description: "A peaceful retreat in the heart of the mountains.",
    image: "/assets/image-0.jpg",
    price: 120,
    location: "Aspen, Colorado",
    country: "USA",
  },
  {
    title: "Luxury Beachfront Villa",
    description: "Wake up to the sound of waves in this stunning villa.",
    image: "/assets/image-1.jpg",
    price: 450,
    location: "Malibu, California",
    country: "USA",
  },
  {
    title: "Modern City Apartment",
    description: "A stylish apartment in the heart of the city.",
    image: "/assets/image-2.jpg",
    price: 200,
    location: "New York City, New York",
    country: "USA",
  },
  {
    title: "Rustic Countryside Cottage",
    description: "Escape to the countryside in this charming cottage.",
    image: "/assets/image-3.jpg",
    price: 90,
    location: "Yorkshire, England",
    country: "UK",
  },
  {
    title: "Charming Lakehouse",
    description: "Enjoy serene lake views from this cozy retreat.",
    image: "/assets/image-4.jpg",
    price: 150,
    location: "Lake Tahoe, California",
    country: "USA",
  },
  {
    title: "Historic Townhouse",
    description: "A beautifully restored townhouse in a historic district.",
    image: "/assets/image-0.jpg",
    price: 300,
    location: "Charleston, South Carolina",
    country: "USA",
  },
  {
    title: "Ski Resort Chalet",
    description: "Perfect for winter getaways with ski-in/ski-out access.",
    image: "/assets/image-1.jpg",
    price: 500,
    location: "Whistler, Canada",
    country: "Canada",
  },
  {
    title: "Tropical Bungalow",
    description: "Relax in this tropical paradise with private beach access.",
    image: "/assets/image-2.jpg",
    price: 350,
    location: "Bali, Indonesia",
    country: "Indonesia",
  },
  {
    title: "Urban Loft",
    description: "A trendy loft in the heart of the city with skyline views.",
    image: "/assets/image-3.jpg",
    price: 275,
    location: "San Francisco, California",
    country: "USA",
  },
  {
    title: "Desert Retreat",
    description: "Experience tranquility in this secluded desert home.",
    image: "/assets/image-4.jpg",
    price: 180,
    location: "Sedona, Arizona",
    country: "USA",
  },
  {
    title: "Victorian Mansion",
    description: "A grand Victorian-era mansion with stunning architecture.",
    image: "/assets/image-0.jpg",
    price: 600,
    location: "Boston, Massachusetts",
    country: "USA",
  },
  {
    title: "Treehouse Getaway",
    description: "Escape into nature with this unique treetop retreat.",
    image: "/assets/image-1.jpg",
    price: 250,
    location: "Portland, Oregon",
    country: "USA",
  },
  {
    title: "Modern Suburban Home",
    description: "A sleek and comfortable home in a suburban neighborhood.",
    image: "/assets/image-2.jpg",
    price: 220,
    location: "Dallas, Texas",
    country: "USA",
  },
  {
    title: "Minimalist Tiny House",
    description: "A compact yet stylish tiny home perfect for simple living.",
    image: "/assets/image-3.jpg",
    price: 80,
    location: "Seattle, Washington",
    country: "USA",
  },
  {
    title: "Lakefront Log Cabin",
    description: "A traditional log cabin with stunning lake views.",
    image: "/assets/image-4.jpg",
    price: 170,
    location: "Ontario, Canada",
    country: "Canada",
  },
];

module.exports = data;
