const data = [
  {
    title: "Cozy Mountain Cabin",
    description: "A peaceful retreat in the heart of the mountains.",
    image: "https://yavuzceliker.github.io/sample-images/image-1.jpg",
    price: 120,
    location: "Aspen, Colorado",
    country: "USA",
  },
  {
    title: "Luxury Beachfront Villa",
    description: "Wake up to the sound of waves in this stunning villa.",
    image: "https://yavuzceliker.github.io/sample-images/image-2.jpg",
    price: 450,
    location: "Malibu, California",
    country: "USA",
  },
  {
    title: "Modern City Apartment",
    description: "A stylish apartment in the heart of the city.",
    image: "https://yavuzceliker.github.io/sample-images/image-3.jpg",
    price: 200,
    location: "New York City, New York",
    country: "USA",
  },
  {
    title: "Rustic Countryside Cottage",
    description: "Escape to the countryside in this charming cottage.",
    image: "https://yavuzceliker.github.io/sample-images/image-4.jpg",
    price: 90,
    location: "Yorkshire, England",
    country: "UK",
  },
  {
    title: "Charming Lakehouse",
    description: "Enjoy serene lake views from this cozy retreat.",
    image: "https://yavuzceliker.github.io/sample-images/image-5.jpg",
    price: 150,
    location: "Lake Tahoe, California",
    country: "USA",
  },
  {
    title: "Historic Townhouse",
    description: "A beautifully restored townhouse in a historic district.",
    image: "https://yavuzceliker.github.io/sample-images/image-6.jpg",
    price: 300,
    location: "Charleston, South Carolina",
    country: "USA",
  },
  {
    title: "Ski Resort Chalet",
    description: "Perfect for winter getaways with ski-in/ski-out access.",
    image: "https://yavuzceliker.github.io/sample-images/image-7.jpg",
    price: 500,
    location: "Whistler, Canada",
    country: "Canada",
  },
  {
    title: "Tropical Bungalow",
    description: "Relax in this tropical paradise with private beach access.",
    image: "https://yavuzceliker.github.io/sample-images/image-8.jpg",
    price: 350,
    location: "Bali, Indonesia",
    country: "Indonesia",
  },
  {
    title: "Urban Loft",
    description: "A trendy loft in the heart of the city with skyline views.",
    image: "https://yavuzceliker.github.io/sample-images/image-9.jpg",
    price: 275,
    location: "San Francisco, California",
    country: "USA",
  },
  {
    title: "Desert Retreat",
    description: "Experience tranquility in this secluded desert home.",
    image: "https://yavuzceliker.github.io/sample-images/image-10.jpg",
    price: 180,
    location: "Sedona, Arizona",
    country: "USA",
  },
];

module.exports = data;
